use_frameworks!

target 'DialExt' do
  pod 'ProtocolBuffers-Swift'
end

target 'DialExt_Example' do
  pod 'DialExt', :path => '../'

  target 'DialExt_Tests' do
    inherit! :search_paths

    
  end
end
