use_frameworks!

target 'DialExt' do
  pod 'ProtocolBuffers-Swift'
  pod 'Sodium'
end

target 'DialExt_Example' do
    #  pod 'DialExt', :path => '../'

  target 'DialExtTests' do
    inherit! :search_paths

    
  end
end
