use_frameworks!

target 'DialExt' do
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.24'
end

target 'DialExt_Example' do
  pod 'DialExt', :path => '../'

  target 'DialExt_Tests' do
    inherit! :search_paths

    
  end
end
