/// Generated by the Protocol Buffers 3.3.2 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.22
/// Source file "req_update.proto"
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers


public struct ReqUpdateRoot {
    public static let `default` = ReqUpdateRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class ReqUpdate : GeneratedMessage {
    public typealias BuilderType = ReqUpdate.Builder

    public static func == (lhs: ReqUpdate, rhs: ReqUpdate) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasMinVersion == rhs.hasMinVersion) && (!lhs.hasMinVersion || lhs.minVersion == rhs.minVersion)
        fieldCheck = fieldCheck && (lhs.hasAppLink == rhs.hasAppLink) && (!lhs.hasAppLink || lhs.appLink == rhs.appLink)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }

    public fileprivate(set) var minVersion:String! = nil
    public fileprivate(set) var hasMinVersion:Bool = false

    public fileprivate(set) var appLink:String! = nil
    public fileprivate(set) var hasAppLink:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() -> Bool {
        return true
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasMinVersion {
            try codedOutputStream.writeString(fieldNumber: 1, value:minVersion)
        }
        if hasAppLink {
            try codedOutputStream.writeString(fieldNumber: 2, value:appLink)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasMinVersion {
            serialize_size += minVersion.computeStringSize(fieldNumber: 1)
        }
        if hasAppLink {
            serialize_size += appLink.computeStringSize(fieldNumber: 2)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> ReqUpdate.Builder {
        return ReqUpdate.classBuilder() as! ReqUpdate.Builder
    }
    public func getBuilder() -> ReqUpdate.Builder {
        return classBuilder() as! ReqUpdate.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return ReqUpdate.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return ReqUpdate.Builder()
    }
    public func toBuilder() throws -> ReqUpdate.Builder {
        return try ReqUpdate.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:ReqUpdate) throws -> ReqUpdate.Builder {
        return try ReqUpdate.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        guard isInitialized() else {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message")
        }

        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasMinVersion {
            jsonMap["minVersion"] = minVersion
        }
        if hasAppLink {
            jsonMap["appLink"] = appLink
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> ReqUpdate {
        return try ReqUpdate.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> ReqUpdate {
        return try ReqUpdate.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasMinVersion {
            output += "\(indent) minVersion: \(minVersion) \n"
        }
        if hasAppLink {
            output += "\(indent) appLink: \(appLink) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasMinVersion {
                hashCode = (hashCode &* 31) &+ minVersion.hashValue
            }
            if hasAppLink {
                hashCode = (hashCode &* 31) &+ appLink.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "ReqUpdate"
    }
    override public func className() -> String {
        return "ReqUpdate"
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
        fileprivate var builderResult:ReqUpdate = ReqUpdate()
        public func getMessage() -> ReqUpdate {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var minVersion:String {
            get {
                return builderResult.minVersion
            }
            set (value) {
                builderResult.hasMinVersion = true
                builderResult.minVersion = value
            }
        }
        public var hasMinVersion:Bool {
            get {
                return builderResult.hasMinVersion
            }
        }
        @discardableResult
        public func setMinVersion(_ value:String) -> ReqUpdate.Builder {
            self.minVersion = value
            return self
        }
        @discardableResult
        public func clearMinVersion() -> ReqUpdate.Builder{
            builderResult.hasMinVersion = false
            builderResult.minVersion = nil
            return self
        }
        public var appLink:String {
            get {
                return builderResult.appLink
            }
            set (value) {
                builderResult.hasAppLink = true
                builderResult.appLink = value
            }
        }
        public var hasAppLink:Bool {
            get {
                return builderResult.hasAppLink
            }
        }
        @discardableResult
        public func setAppLink(_ value:String) -> ReqUpdate.Builder {
            self.appLink = value
            return self
        }
        @discardableResult
        public func clearAppLink() -> ReqUpdate.Builder{
            builderResult.hasAppLink = false
            builderResult.appLink = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> ReqUpdate.Builder {
            builderResult = ReqUpdate()
            return self
        }
        override public func clone() throws -> ReqUpdate.Builder {
            return try ReqUpdate.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> ReqUpdate {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> ReqUpdate {
            let returnMe:ReqUpdate = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:ReqUpdate) throws -> ReqUpdate.Builder {
            if other == ReqUpdate() {
                return self
            }
            if other.hasMinVersion {
                minVersion = other.minVersion
            }
            if other.hasAppLink {
                appLink = other.appLink
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> ReqUpdate.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> ReqUpdate.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 10:
                    minVersion = try codedInputStream.readString()

                case 18:
                    appLink = try codedInputStream.readString()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> ReqUpdate.Builder {
            let resultDecodedBuilder = ReqUpdate.Builder()
            if let jsonValueMinVersion = jsonMap["minVersion"] as? String {
                resultDecodedBuilder.minVersion = jsonValueMinVersion
            }
            if let jsonValueAppLink = jsonMap["appLink"] as? String {
                resultDecodedBuilder.appLink = jsonValueAppLink
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> ReqUpdate.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try ReqUpdate.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension ReqUpdate: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<ReqUpdate> {
        var mergedArray = Array<ReqUpdate>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> ReqUpdate? {
        return try ReqUpdate.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(data: data, extensionRegistry:ReqUpdateRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> ReqUpdate {
        return try ReqUpdate.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "minVersion": return self.minVersion
        case "appLink": return self.appLink
        default: return nil
        }
    }
}
extension ReqUpdate.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = ReqUpdate
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "minVersion": return self.minVersion
            case "appLink": return self.appLink
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "minVersion":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.minVersion = newSubscriptValue
            case "appLink":
                guard let newSubscriptValue = newSubscriptValue as? String else {
                    return
                }
                self.appLink = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
